language: go

go:
  - 1.9.7

before_install:
  - go get -t -v ./...
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y


install:
  - glide install
  - glide update

script:
  - make test

script:
  - go test -race ./helper -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 69c14921-3f67-4304-b058-8c7321d80557